<?php

$animals = ["Chat", "Chien", "Souris", "Lama"];

?>


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Exercice 3 echo</title>
	</head>
	<body>
	    
	    <ul>
	        
	        
	  <?php for ($i = 0; $i < count($animals); $i++) { ?>
	  
	  
	  <li>
	      <?php echo "$animals[$i]\n"; ?>
	  </li>
	    
	    <?php } ?>
	        
	        
	    </ul>
	    
	</body>
</html>